openapi: "3.1.0"
info:
  version: 1.0.0
  title: Pokemon API
  license:
    name: MIT
servers:
  - url: http://localhost/api

tags:
  - name: Pokemons
  - name: Locations
  - name: Abilities

paths:
  /pokemons:
    $ref: "./paths/pokemons.yaml#/indexRequest"

  /pokemons/{id}:
    $ref: "./paths/pokemons.yaml#/showRequest"

  /locations:
    $ref: "./paths/locations.yaml#/indexRequest"

  /locations/{id}:
    $ref: "./paths/locations.yaml#/showRequest"

  /abilities:
    $ref: "./paths/abilities.yaml#/indexRequest"

  /abilities/{id}:
    $ref: "./paths/abilities.yaml#/showRequest"

