openapi: "3.1.0"
info:
  version: 1.0.0
  title: Pokemon API
  license:
    name: MIT
servers:
  - url: http://localhost/api

paths:
  /locations:
    $ref: "./paths/locations.yaml#/indexRequest"

  /locations/{id}:
    $ref: "./paths/locations.yaml#/showRequest"

